
export default function WhatIs_heroku() {
  return (
    <>
      <div className="mx-auto max-w-5xl py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0 flex items-center">
          <div className="sm:h-50 flex flex-col">
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Heroku is a cloud platform as a service (PaaS) that enables developers to deploy, manage, and scale 
              applications without the need for infrastructure management. It was founded in 2007 and was acquired by 
              Salesforce in 2010.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 "
              style={{ color: '' }}
            >
              Heroku supports a variety of programming languages and frameworks, including Node.js, Ruby, Java, Python, 
              PHP, and Go. With Heroku, developers can easily deploy their applications to the cloud using a simple 
              command-line interface or a web-based dashboard.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Heroku provides a number of features that make it easy to deploy and manage applications, including:
            </h2>

            <ul className="m-8">
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                1. Automatic scaling: Heroku can automatically scale your application to handle increases in traffic and demand.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                2. Add-ons: Heroku provides a marketplace of third-party add-ons that can be easily integrated into your application, such as databases, caching services, and logging tools.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                3. Buildpacks: Heroku uses buildpacks to automatically detect and configure your application's dependencies, making it easy to deploy your code.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                4. Collaboration: Heroku provides a collaborative workflow that enables multiple developers to work on the same application at the same time.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                5. Integration: Heroku integrates with a variety of other tools and services, such as GitHub, Slack, and Salesforce, making it easy to build and deploy applications that work seamlessly with other tools.
              </li>
            </ul>
            
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Overall, Heroku is a powerful and flexible platform that simplifies the process of deploying, managing, 
              and scaling applications in the cloud, enabling developers to focus on building and delivering great software.
            </h2>

            <p className="text-l font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8">
              - text generated by ChatGPT
            </p>
          </div>
        </div>
      </div>
    </>
  )
}