
export default function WhatIs_mongodb() {
  return (
    <>
      <div id='mongodb' className="mx-auto max-w-5xl py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0 flex items-center">
          <div className="sm:h-50 flex flex-col">
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              MongoDB is a document-oriented NoSQL database that stores data in flexible, semi-structured documents in 
              JSON-like format, called BSON. It was developed by MongoDB Inc. and released in 2009. MongoDB is designed 
              to scale horizontally across multiple servers and to handle large volumes of unstructured or semi-structured 
              data.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 "
              style={{ color: '' }}
            >
              One of the main advantages of MongoDB is its flexibility and scalability. Its document-oriented data model 
              allows for the storage of complex and heterogeneous data structures that can be easily updated and extended. 
              MongoDB also supports dynamic schema, which means that documents can have different fields and structures 
              without the need for pre-defined schema.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              MongoDB provides a rich query language that supports a wide range of operations for reading, writing, and 
              modifying data. It also supports aggregation pipelines for performing complex queries and data transformations.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              MongoDB has a large and active community that has developed many open-source tools, libraries, and frameworks 
              for working with MongoDB, including drivers for various programming languages and frameworks, such as 
              Node.js, Python, Java, and Ruby.
            </h2>
            <p className="text-l font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8">
              - text generated by ChatGPT
            </p>
          </div>
        </div>
      </div>
    </>
  )
}