
export default function WhatIs_nextjs() {
  return (
    <>
      <div className="mx-auto max-w-5xl py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0 flex items-center">
          <div className="sm:h-50 flex flex-col">
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Next.js is an open-source framework for building server-side rendered (SSR) React applications. 
              It was developed by Vercel (formerly Zeit) and released in 2016. Next.js provides a set of tools 
              and features that make it easy to build complex, production-ready applications with React, without 
              having to configure complex build tools or server-side rendering yourself.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 "
              style={{ color: '' }}
            >
              Next.js supports a variety of rendering modes, including server-side rendering, static site 
              generation, and client-side rendering. It also provides a number of features that make it easy to 
              build fast and scalable web applications, including:
            </h2>

            <ul className="m-8">
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                1. Automatic code splitting: Next.js automatically splits your code into smaller chunks and only loads the code that is 
                needed for each page, which improves performance and reduces load times.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                2. Built-in CSS support: Next.js provides built-in support for CSS modules and styled components, which make it easy to style your React components and keep your styles organized.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                3. Image optimization: Next.js provides built-in image optimization, which automatically optimizes images for faster loading times and better performance.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
               4. API routes: Next.js provides built-in API routes, which make it easy to build backend functionality for your application without having to set up a separate server.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
               5. Static site generation: Next.js supports static site generation, which allows you to generate static HTML pages for your application at build time, which can improve performance and SEO.
              </li>
            </ul>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Overall, Next.js is a powerful and flexible framework for building server-side rendered React 
              applications, which provides a wide range of features and tools that make it easy to build fast, 
              scalable, and production-ready web applications.
            </h2>
            <text className="text-l font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8">
              - text generated by ChatGPT
            </text>
          </div>
        </div>
      </div>
    </>
  )
}