
export default function WhatIs_nodejs() {
  return (
    <>
      <div className="mx-auto max-w-5xl py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0 flex items-center">
          <div className="sm:h-50 flex flex-col">
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Node.js is an open-source, cross-platform, server-side runtime environment built on the V8 JavaScript 
              engine of the Google Chrome web browser. It allows developers to build scalable and high-performance 
              applications using JavaScript on the server-side.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 "
              style={{ color: '' }}
            >
              Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, and it 
              supports asynchronous programming that enables handling of a large number of concurrent connections. 
              It can be used to build various types of applications, including web applications, RESTful APIs, 
              real-time applications, and command-line tools.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              One of the main advantages of Node.js is its large and active community, which has developed a rich 
              ecosystem of modules and packages that can be easily installed using the Node Package Manager (NPM). 
              This makes it easy to use third-party libraries to add functionality to Node.js applications and to 
              share code with other developers.
            </h2>
            <p className="text-l font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8">
              - text generated by ChatGPT
            </p>
          </div>
        </div>
      </div>
    </>
  )
}