
export default function WhatIs_graphql() {
  return (
    <>
      <div className="mx-auto max-w-5xl py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0 flex items-center">
          <div className="sm:h-50 flex flex-col">
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              React is an open-source JavaScript library for building user interfaces (UIs) or front-end web applications. 
              It was developed by Facebook and released in 2013. React is now widely used by developers all over the world 
              to build complex and interactive UIs for web applications and mobile apps.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 "
              style={{ color: '' }}
            >
              React follows a component-based architecture, where UI elements are broken down into small, reusable pieces called 
              components. These components can be combined to create complex user interfaces. React uses a 
              virtual DOM (Document Object Model), which is a lightweight copy of the actual DOM, to update the user 
              interface efficiently and quickly, without the need for full-page refreshes.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              React is also highly extensible and can be easily integrated with other libraries and frameworks. It provides a 
              rich set of features that make it easy to build dynamic and interactive UIs, including:
            </h2>

            <ul className="m-8">
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                1. JSX: React uses a syntax called JSX that enables developers to write HTML-like code in their JavaScript code, making it easier to create UI components.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                2. State management: React provides a simple and efficient way to manage the state of a component, which is used to keep track of data and render changes to the UI.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                3. Hooks: React provides hooks, which are functions that allow developers to use state and other React features without writing a class component.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                4. React Native: React can be used to build mobile applications using React Native, a framework that enables developers to build native mobile apps for iOS and Android using React.
              </li>
            </ul>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Overall, React is a powerful and flexible library for building user interfaces that is widely used and supported by a large and active community of developers.
            </h2>

            <text className="text-l font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8">
              - text generated by ChatGPT
            </text>
          </div>
        </div>
      </div>
    </>
  )
}