
export default function WhatIs_reactnative() {
  return (
    <>
      <div className="mx-auto max-w-5xl py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0 flex items-center">
          <div className="sm:h-50 flex flex-col">
            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              React Native is an open-source framework for building mobile applications using JavaScript and 
              React. It was developed by Facebook and released in 2015. React Native allows developers to 
              build native mobile applications for iOS and Android platforms using a single codebase, 
              instead of having to write separate code for each platform.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 "
              style={{ color: '' }}
            >
              React Native works by providing a set of pre-built components and APIs that allow developers to 
              build mobile apps using a similar approach to building web applications with React. React Native 
              apps are built using JavaScript and run on a native mobile app runtime, allowing them to take full 
              advantage of the platform's native capabilities.
            </h2>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              React Native provides a number of features that make it easy to build mobile apps, including:
            </h2>

            <ul className="m-8">
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                1. Cross-platform compatibility: React Native allows developers to write code once and deploy it to both iOS and Android platforms.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                2. Native performance: React Native apps are compiled into native code, which provides better performance than hybrid or web-based mobile apps.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                3. Pre-built components: React Native provides a set of pre-built components that are optimized for mobile devices, such as buttons, forms, and lists.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                4. Hot reloading: React Native provides a feature called "hot reloading", which allows developers to see changes in their code immediately without 
                having to rebuild the entire app.
              </li>
              <li className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8 ">
                5. Third-party libraries: React Native supports a wide range of third-party libraries and plugins that can be used to add functionality to your app, 
                such as navigation, analytics, and social sharing.
              </li>
            </ul>

            <h2
              className="sm:text-2xl lg:text-2xl font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8"
              style={{ color: '' }}
            >
              Overall, React Native is a powerful and flexible framework for building native mobile applications using JavaScript and React, which can help developers save time and resources while delivering high-quality mobile apps.
            </h2>

            <text className="text-l font-bold tracking-tight font-subtext sm:w-10/12 md:w-11/12 m-4 mx-8">
              - text generated by ChatGPT
            </text>
          </div>
        </div>
      </div>
    </>
  )
}